### ISSUE TITLE
Use of lambertw function in preprocessing of log returns

### ISSUE THREAD

**Issue by leighhopcroft** [CasperHogenboom/WGAN_financial_time-series#1]
Could you explain exactly what is happening in the preprocessing of the log returns in data.py? Specifically:

log_returns_w = (np.sign(log_returns)*np.sqrt(lambertw(self.delta*log_returns**2)/self.delta)).real

**Comment by CasperHogenboom** [comment]
Hey!

I implemented a lambert W transform on the Gaussian distribution. This will
‘scale’ the outliers in the tails of the heavy tailed Gaussian to more
‘Normal’ like distribution. It is also transformed back with inverse.

It has been a while, but that is how I remember it :) think I used this as
reference;

https://www.hindawi.com/journals/tswj/2015/909231/



Op do 20 jan. 2022 om 20:23 schreef leighhopcroft ***@***.***>

**Comment by leighhopcroft** [comment]
Nice, thanks for the explanation and the link!
